services:
  - type: web
    name: exactosbc
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    preDeployCommand: pnpm prisma db push --accept-data-loss && pnpm tsx src/server/scripts/setup.ts
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        value: us-east-1
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_PUBLIC_URL
        sync: false
