#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

# install dependencies, generate prisma client, push schema, seed data
pnpm install
pnpm exec prisma db push --accept-data-loss
pnpm exec tsx src/server/scripts/setup.ts
